### ISSUE TITLE
Does it work with AdobeAcrobatReader? 

### ISSUE THREAD

**Issue by ACC21** [juanerasmoe/PDFHighlightExtractor#1]
Hello, 
could you tell me if I can use this PDFHighlightExtractor with Preview or AdobeAcrobatReader?
Does it automatically copy my highlighted text into a comment? 
I am using Docear on a Mac and with AdobeAcrobatReader.
I am looking forward hearing from you!

**Comment by baracunatana** [comment]
Yes, it should work.
It'll copy the text to the highlight comment and you'll be able to import it in Docear.
Give it a try and let me know if it works for you

**Comment by ACC21** [comment]
Hej, 
I tried it, but unfortunately it doesn't work. I just downloaded it and tried to open it by clicking on Licence.exec Then it says:
xxs-MacBook-Pro:~ xx$ /Users/xx/Desktop/PDFHighlightExtractor-master/LICENSE ; exit;
/Users/xx/Desktop/PDFHighlightExtractor-master/LICENSE: line 1: GNU: command not found
/Users/xx/Desktop/PDFHighlightExtractor-master/LICENSE: line 2: Version: command not found
/Users/xx/Desktop/PDFHighlightExtractor-master/LICENSE: line 4: syntax error near unexpected token `C'
/Users/xx/Desktop/PDFHighlightExtractor-master/LICENSE: line 4:` Copyright (C) 1989, 1991 Free Software Foundation, Inc., http://fsf.org/'
logout

[Prozess beendet]

Could you help me with that? I would really appreciate to use it! 
THX!

**Comment by baracunatana** [comment]
I don't understand. Did you downloaded the .jar file?

**Comment by ACC21** [comment]
Yes, I downloaded everything by clicking on "download ZIP". Then I opened the file and tried to launch the pdfbox-app-1.8.9.jar, but it says "The Jar file couldn't be launched, check the console for possible error massages". But unfortunately I can't find an error message there.
Should I have done something else to open the PDFHighlightExtractor? Or do you know if it works with Mac OS X 10.10.5 and java 1.8.0_60? 
I would be grateful for any help. 
THX!

**Comment by baracunatana** [comment]
Thats not the right file. Download the executable from https://github.com/juanerasmoe/PDFHighlightExtractor/releases
It's the one ending in .jar
